name: CI/CD

push:
  branches: [main]
  paths-ignore: ["**/README.md"]
pull_request:
  branches: [main]
  types: [opened, synchronize]
  paths-ignore: ["**/README.md"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint --if-present

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test --if-present
